### ISSUE TITLE
异步读写Benchmark例子不合理

### ISSUE THREAD

**Issue by xpiaoyu** [smallnest/ringbuffer#3]
例如 `BenchmarkRingBuffer_AsyncWrite` 这个方法

```
...
for i := 0; i < b.N; i++ {
    rb.Read(buf)
}
...
```

大量的Read返回的是 `0, ErrIsEmpty`，因此不能很好反应该Buffer的实际性能。

**Comment by smallnest** [comment]
为什么不能反应wirte的性能，如果有问题应该如何改进？需要描述一下。

**Comment by xpiaoyu** [comment]
```
errCnt := 0
b.ResetTimer()
for i := 0; i < b.N; i++ {
	_, err := rb.Read(buf)
	if err != nil {
		errCnt++
		runtime.Gosched()
	}
}
b.StopTimer()
b.Log(errCnt, b.N)
```

发生错误时说明写入速度跟不上读出速度，让出CPU，能够减少errCnt大小。
`ring_buffer_benchmark_test.go:59: 1198269 4574940` 大约 270 ns/op

如果不执行 `runtime.Gosched()` errCnt与实际执行次数差距很小。
`ring_buffer_benchmark_test.go:58: 19833798 21876571` 大约 46.3 ns/op

**Comment by smallnest** [comment]
是的，第27行和第44行应该处理err,如果是ErrIsEmpty、ErrIsFull调用`runtime.Gosched()`
