### ISSUE TITLE
rewrite it by go1.18 generic

### ISSUE THREAD

**Issue by YiuTerran** [smallnest/ringbuffer#6]
泛型替换掉`[]byte`。而且新版本支持TryLock了，代码可以大幅度简化。
mu可以替换成读写锁，性能应该可以优化一些。

**Comment by smallnest** [comment]
本来此库就是用来处理byte slice,包括内部的处理和aou也是为了io.reader,writer,所以不适合用。T替换[]byte.
其它的优化可以做

**Comment by yuikns** [comment]
泛型化后尝试稍微做了些简单的 benchmark，看起来这个性能是可以对齐的： https://github.com/argcv/ringbuffer/blob/benchmark-analysis/REPORT.md （如考虑有错请求指正）

请问现在是否还是考虑限定 byte slice only?
